### Login correcto
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "username": "cdiaz",
    "password": "cdiaz123"
}

### Login correcto
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "username": "jechavarria",
    "password": "jechavarria123"
}
