###
GET http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZWNoYXZhcnJpYSIsImlhdCI6MTc2MTYxOTQ1MywiZXhwIjoxNzYxNjE5NzUzfQ.CSyWq7u2lz3d3ourUEj2oJG-i518_MgCsTSLVsjVAAw
Accept: application/json

###
POST http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjZGlheiIsImlhdCI6MTc2MTYxOTQxMCwiZXhwIjoxNzYxNjE5NzEwfQ.DFktsXbLRhLTskPnKkvRAwEeUXrXzeRdCn_FwLvVPxU
Content-Type: application/json

{
    "full_name": "Uber Torres",
    "username": "utorres",
    "password": "utorres123",
    "email": "utorres@email.com",
    "role": "USER"
}