###
GET http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiSm9yZ2UgQW5kcmVzIEVjaGF2YXJyaWEiLCJyb2xlIjoiVVNFUiIsInN1YiI6ImplY2hhdmFycmlhIiwiaWF0IjoxNzYxNjIyNTEyLCJleHAiOjE3NjE2MjI4MTJ9.jT0Gs6KSxuQAUTMkB_ED763HAQ05F2PmMJ--QavHhQs
Accept: application/json

###
POST http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiQ2VzYXIgQXVndXN0byBEaWF6Iiwicm9sZSI6IkFETUlOIiwic3ViIjoiY2RpYXoiLCJpYXQiOjE3NjE2MjI2MzksImV4cCI6MTc2MTYyMjkzOX0.P7uebBXCAfhWmmLbthFK2rLnngTWxb7OJHiEa9cWups
Content-Type: application/json

{
    "full_name": "Uber Torres",
    "username": "utorres",
    "password": "utorres123",
    "email": "utorres@email.com",
    "role": "USER"
}